# Generated by Django 3.1.1 on 2020-09-17 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('ExamManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(default=0)),
                ('exam', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ExamManagement.exam')),
                ('examinee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.examinee')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(default=0)),
                ('time', models.IntegerField(default=1)),
                ('exam', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ExamManagement.exam')),
                ('examinee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.examinee')),
            ],
        ),
        migrations.CreateModel(
            name='ExamineeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('marks', models.FloatField(default=0)),
                ('right', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('exam', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ExamManagement.exam')),
                ('examinee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.examinee')),
            ],
        ),
    ]
