# Generated by Django 3.1.1 on 2020-09-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='marks',
            field=models.FloatField(default=0, null=True),
        ),
    ]
