# Generated by Django 3.1.2 on 2020-10-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultManagement', '0003_result_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='exam/returns'),
        ),
    ]
