# Generated by Django 3.1.1 on 2020-09-15 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.IntegerField()),
                ('exam_title', models.CharField(max_length=200)),
                ('exam_marks', models.IntegerField()),
                ('exam_date_time', models.DateTimeField()),
                ('exam_duration', models.CharField(max_length=20)),
                ('examiner_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  to='Accounts.examiner')),
            ],
        ),
    ]
