# Generated by Django 3.1.1 on 2020-09-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='examiner_id',
            new_name='examiner',
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_marks',
            field=models.IntegerField(default=100),
        ),
    ]
