# Generated by Django 3.1.1 on 2020-09-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquestion',
            name='ques_marks',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='ques_marks',
            field=models.IntegerField(default=1),
        ),
    ]
