# Generated by Django 3.1.1 on 2020-09-15 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Accounts', '0001_initial'),
        ('ExamManagement', '0002_auto_20200916_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptedExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamManagement.exam')),
                ('examinee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.examinee')),
            ],
        ),
    ]
