# Generated by Django 3.1.1 on 2020-09-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManagement', '0003_exam_exam_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptedexam',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
