# Generated by Django 3.1.1 on 2020-09-16 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManagement', '0003_attemptedexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=100)),
                ('time_limit', models.IntegerField(default=60)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamManagement.exam')),
            ],
        ),
    ]
