# Generated by Django 3.1.2 on 2020-10-04 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManagement', '0004_attemptedexam_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptedexam',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamManagement.exam'),
        ),
    ]
