# Generated by Django 3.1.1 on 2020-09-16 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManagement', '0005_mcq_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamManagement.questions')),
            ],
        ),
    ]
