# Generated by Django 3.1.1 on 2020-09-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ExamManagement', '0001_initial'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamineeCustomAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('custom_question', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamManagement.customquestion')),
                ('examinee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.examinee')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corr_ans', models.CharField(max_length=200)),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ExamManagement.mcqquestion')),
            ],
        ),
    ]
