# Generated by Django 3.1.1 on 2020-09-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('ExamManagement', '0006_custom_questions'),
        ('AnswerManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamManagement.mcq_questions'),
        ),
        migrations.CreateModel(
            name='ExamineeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_option', models.CharField(blank=True, max_length=200, null=True)),
                ('custom_answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('custom_question', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamManagement.custom_questions')),
                ('examinee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.examinee')),
                ('mcq_question', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamManagement.mcq_questions')),
            ],
        ),
    ]
