# Generated by Django 3.1.1 on 2020-09-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManagement', '0001_initial'),
        ('Accounts', '0001_initial'),
        ('AnswerManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamineeMCQAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_option', models.CharField(blank=True, max_length=200, null=True)),
                ('examinee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.examinee')),
                ('mcq_question', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamManagement.mcqquestion')),
            ],
        ),
    ]
