# Generated by Django 3.1.1 on 2020-09-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerManagement', '0005_auto_20200929_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='examineecustomanswer',
            name='marks',
            field=models.BooleanField(default=False),
        ),
    ]
