# Generated by Django 3.1.2 on 2020-10-04 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_remove_verification_is_verified'),
        ('ExamManagement', '0004_attemptedexam_submit'),
        ('AnswerManagement', '0006_examineecustomanswer_marks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamineeCustomAnswer',
            new_name='ExamineeAnswer',
        ),
    ]
