# Generated by Django 3.1.1 on 2020-09-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pro_pic',
            field=models.ImageField(blank=True, default='images/profile/Default.jpg', null=True, upload_to='images/profile'),
        ),
    ]
