# Generated by Django 3.1.2 on 2020-10-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='is_verified',
        ),
    ]
