# Generated by Django 3.1.1 on 2020-09-15 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('ExamManagement', '0002_auto_20200916_0106'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(default=0)),
                ('exam',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ExamManagement.exam')),
                ('examinee',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.examinee')),
            ],
        ),
    ]
